### ISSUE TITLE
Storage check improvements

### ISSUE THREAD

**Issue by jonathanKingston** [biancadanforth/web-dev-experiments#1]
Because localForage can actually get the keys for us (this a the main down side to localstorage), it would be nice if you could duplicate the experiment and show how setting the website as the top key would be. I suspect the speed should be the same/similar and we will have a much neater storage object.

A more real world test would be to update the timestamp on all of the elements in the table:
Dexie:
```js 
async function setSingle(i) {
  console.time('setSingle')
  await db.websites.update(`www.${i}.com`, {
    dateVisited: Date.now()
  });
  console.timeEnd('setSingle');
}

async function setManySingles() {
  console.time('setManySingles')
  for (let i = 0; i<numElements; i++) {
    await setSingle(i);
  }
  console.timeEnd('setManySingles')
}

setManySingles();
```
Localforage:
```js
async function setSingle(i) {
  console.time('setSingle')
  const websites = await localforage.getItem('websites');
  websites[`www.${i}.com`].dateVisited = Date.now();
  await localforage.setItem('websites', websites);
  console.timeEnd('setSingle');
}

async function setManySingles() {
  console.time('setManySingles')
  for (let i = 0; i<numElements; i++) {
    await setSingle(i);
  }
  console.timeEnd('setManySingles')
}

setManySingles();
```

Even with doing this it seems localForage is much faster still which I find pretty odd. Could you also check the individual updating as mentioned above, this should be even faster at this operation.

I think having a database of 10000 isn't that unrealistic for a weeks browsing, so perhaps filling the database with that many and accessing indexes randomly in the middle somewhere (these would have to be in a fixed array though otherwise would add perf unreliability).

I have some worry in that both of these are not blocking correctly, can you change the code to be:

```
async function perfCheck() {
  await clearAllDatabaseFromBefore();
  await setAll()
  await setManySingles();
  await getMostRecentSite();
  await getLastThreeSites();

}
```

Looks like the localforage `performOtherOps` does a `getAll` for both `getMostRecentSite` and `getLastThreeSites` I think this should be done for both to make it similar to the Dexie and more like how we would use it in lightbeam. (I don't suspect it will make much difference though).

I have some concern that we are not clearing the databases consistently, on page refresh localforage appears to be faster than the initial pageload.

Also you might want to try the npm module `http-server` and point it at your `web-dev-experiments` dir and checkout the urls in the browser: `http://127.0.0.1:8080/localforage-for-lightbeam/`this allows you to inspect the database in dev tools.

**Comment by jonathanKingston** [comment]
Also it's worth noting because of the key structure of dexie we don't need to await the setManySingles like we do in the current localforage setup.

My results were roughly:
- 634.71ms - dexie non block
- 3181.72ms - dexie block
- 15106.77ms - localforage

It's also worth noting you might want to run in many times as I saw the dexie blocking result at around 2000ms when I first wrote it.

Also it might be worth trying to play with the number of indexes of that you have in dexie. Also I suspect because of the date index finding items older than a week would be super cheap because of http://dexie.org/docs/WhereClause/WhereClause.above().html.

Finding isVisible is likely something else that would be cheaper too if that were an index. Not sure on the best way to make a deterministic check on this though.

**Comment by biancadanforth** [comment]
> Because localForage can actually get the keys for us (this a the main down side to localstorage), it would be nice if you could duplicate the experiment and show how setting the website as the top key would be. I suspect the speed should be the same/similar and we will have a much neater storage object.

Okay I reimplemented localforage to use each website object as a top level key.

> A more real world test would be to update the timestamp on all of the elements in the table

Okay I've added these two methods for both localforage and Dexie, and have a timer for `setSingle` in addition to `setManySingles`.

>  Could you also check the individual updating as mentioned above, this should be even faster at this operation.

Done.

>  have some worry in that both of these are not blocking correctly, can you change the code to be...

Yes!

> Looks like the localforage performOtherOps does a getAll for both getMostRecentSite and getLastThreeSites I think this should be done for both to make it similar to the Dexie and more like how we would use it in lightbeam. (I don't suspect it will make much difference though).

Hm... not sure I follow here. Currently, these methods in `localforage` use the local clone of `websites` to sort and get the right data; but I don't do a `getAll` explicitly. In `Dexie`, I use various filtering methods like `orderBy`... Are you saying we don't want to take advantage of these methods in Dexie? I thought that might be one point of comparison (how much faster it is to filter with some pre-made Dexie methods versus built-in JS methods)?

> I have some concern that we are not clearing the databases consistently, on page refresh localforage appears to be faster than the initial pageload.

I now clear both databases before running each script.

> Also you might want to try the npm module http-server and point it at your web-dev-experiments dir and checkout the urls in the browser: http://127.0.0.1:8080/localforage-for-lightbeam/ this allows you to inspect the database in dev tools.

Wow that is amazing! TIL. Thanks.

![http-server inspect database in devtools](https://user-images.githubusercontent.com/17437436/28808829-1c854116-7634-11e7-9751-1f153b0e6006.png)

> Also it's worth noting because of the key structure of dexie we don't need to await the setManySingles like we do in the current localforage setup.

Can you explain what you mean here? What do the implementations look like for Dexie non-block, Dexie block and localforage?

> finding items older than a week would be super cheap because... .above method...

Yes Dexie has a lot of pre-made common filtering methods which make it easy to do these checks.

> Finding isVisible is likely something else that would be cheaper too if that were an index. Not sure on the best way to make a deterministic check on this though.

What do you mean by a deterministic check? I can add it as an index and use the same method I use to create `firstPartyHostnames` and `thirdPartyHostnames`, namely: even indices are first parties and odd indices are third parties.

I implemented the following methods in both libraries using fake data I generated in JavaScript, with N = 10000 websites:
* `clearAllDatabaseFromBefore` (localforage: ~107.51ms, Dexie: ~3.25ms)
* `setAll` (localforage: ~10099.65ms, Dexie: ~2578.13ms)
* `getAll` (localforage: ~6582.97ms, Dexie: ~138.51ms)
* `setSingle` (localforage: ~3.51ms, Dexie: ~3.03ms)
* `setManySingles` (localforage: ~15310.61ms, Dexie: ~17209.04ms)
* `getRandomSet` (localforage: ~39.94ms, Dexie: ~12.84ms)
* `getMostRecentSite` (localforage: ~10.99ms, Dexie: ~4.42ms)
* `getLastThreeSites` (localforage: ~25.28ms, Dexie: ~4.27ms)

Now it seems like Dexie is better. I guess before I wasn't comparing apples to apples? Why do you think Dexie is more efficient?

**Comment by jonathanKingston** [comment]
> Can you explain what you mean here? What do the implementations look like for Dexie non-block, Dexie block and localforage?

Essentially my code was:
```
async function setManySingles() {
  console.time('setManySingles')
  for (let i = 0; i<numElements; i++) {
    await setSingle(i);
  }
  console.timeEnd('setManySingles')
}
```

or
```
async function setManySingles() {
  console.time('setManySingles')
  for (let i = 0; i<numElements; i++) {
    setSingle(i);
  }
  console.timeEnd('setManySingles')
}
```

So the difference is that we don't block on setting the row to set the next, this row level locking won't really be needed in Lightbeam if the database uses hostname keys instead of the top level websites key. (yes we might visit the same 1st or 3rd party at the same time but the loss of data would be minimal/not at all).

As we are moving to an async database, we increase the need for locking of the data, however as mentioned I don't think we need to worry too much a bout it.

**Comment by jonathanKingston** [comment]
> Now it seems like Dexie is better. I guess before I wasn't comparing apples to apples? Why do you think Dexie is more efficient?

It's worth noting that `setAll` is likely the least interesting operation here due to us never likely needing this besides a restore of a backup. Get all for this size of data is worrying for localforage (will check the code in a second).

However the main reason I think dexie is better for certain operations is that it seems like localforage doesn't have indexes which means certain queries are unlikely to always to be faster. However the more indexes you have the more it will impact write performance (unless some magic happens on dexies end).

It is worth noting that besides getAll these numbers aren't wildly apart from each other here. I will check over the code again and see if there are other issues.

**Comment by jonathanKingston** [comment]
> Yes Dexie has a lot of pre-made common filtering methods which make it easy to do these checks.

By cheap I mean more efficient performance wise than the reverse and filter crap that seems to be needed :( also cheaper than filtering yourself.

> What do you mean by a deterministic check?

Selecting a random item using `Math.random` or similar wouldn't be deterministic in that the 1st item would be cheap and so on. If you wanted to scatter isVisible data "randomly" through the rows, it would need to be deterministic with both localforage and dexie setups and be consistent between reload of the data. I dunno maybe you could use factorals or something like that.
Having a completely even distribution might help the algos of one engine to another, what we want to check is in "real" data that is always the same on every load does the index improve the situation.

**Comment by jonathanKingston** [comment]
> Currently, these methods in localforage use the local clone of websites to sort and get the right data; but I don't do a getAll explicitly

The issue was with the localForage implementation here, you are calling a cloned getAll which isn't realistic.

**Comment by jonathanKingston** [comment]
`Math.round(Math.random() * numElements)` generate these once and hard code them. Randomness is what I was talking about being an issue.

Where by I mean creating an array like:
```
[2, 12, 105...
```
This would go into both implementations as the same.

**Comment by jonathanKingston** [comment]
If there isn't a native method to `getAll` then this should likely not block on each item (this is likely the perf issue)

```
async function getAll() {
  console.time('getAll');
  websites = [];
  for (let i = 0; i < numElements; i++) {
    websites.push(localforage.getItem(`www.${i}.com`));
  }
  const resolvedWebsites = await Promise.all(websites);
  console.timeEnd('getAll');
  return resolvedWebsites;
}
```

**Comment by jonathanKingston** [comment]
Also a big improvement we can likely do in an indexed database is filter such that on the graph we draw each day going back into history at a time. So the graph would only have to draw a day of nodes on initial render then would keep going back into time to draw the rest.

**Comment by jonathanKingston** [comment]
For the isVisible check maybe using Fibonacci numbers would be good enough to making the random set of data through the database. Ignoring duplicates and first parties at those index.

**Comment by biancadanforth** [comment]
Okay I broke out `setManySingles` into `setManySinglesBlocking` and `setManySinglesUnblocking`, and as expected, Unblocking is much faster (about 5X).

I also made the `getRandomSet` method deterministic by using a fixed set of random indices each time the test is run.

I added the `isVisible` index and used Fibonacci numbers as you suggested to randomize (in a deterministic way; deterministic: that's my word of the day) the distribution of visible websites in the database.

I have also added a new method `getLastThreeDaysVisibleSites` (a mouthful!). This does a more advanced filter by first finding all the sites in the last 3 days, and then filtering for those which have `isVisible` set to true (or 1). Note that Dexie does not accept boolean values for indices.

I also fixed the localforage implementation of `getAll` so that it's not blocking for each request (no, there isn't a localforage method for this). It makes sense to me that we can make all the `getItem` at once and only return a value once they've all come back rather than waiting for the previous call to return before calling the next.

I have added an explicit call to `getAll` in the implementations for `getMostRecentSite`, `getLastThreeSites` and `getLastThreeDaysVisibleSites`.

Note that ALL websites currently are within the last 3 days, since we use `Date.now()` to update the `dateVisited` index in `setManySingles`. However, it is correctly returning this, and filtering that again for `isVisible` equal to 1.

**Comment by biancadanforth** [comment]
New test results with N = 10000 websites:
* `clearAllDatabaseFromBefore` (localforage: ~50ms, Dexie: ~3ms)
* `setAll` (localforage: ~6554ms, Dexie: ~2265ms)
* `getAll` (localforage: ~2491ms, Dexie: ~120ms)
* `setSingle` (localforage: ~6ms, Dexie: ~3ms)
* `setManySinglesBlocking` (localforage: ~14611ms, Dexie: ~15640ms)
*  `setManySinglesUnblocking` (localforage: ~579ms, Dexie: ~3003ms)
* `getRandomSet` (localforage: ~8354ms, Dexie: ~1149ms)
* `getMostRecentSite`^ (localforage: ~2704ms, Dexie: ~14ms)
* `getLastThreeSites`^ (localforage: ~2420ms, Dexie: ~5ms)
* `getLastThreeDaysVisibleSites`^ (localforage: ~2732ms, Dexie: ~541ms)

^: Now includes a `getAll` in localforage version

**Conclusion**: Dexie is either similar or faster than localforage in virtually all methods used.

**Comment by biancadanforth** [comment]
[JSPerf](https://jsperf.com/) test results with N = 100^ websites (units: Ops/s):
* `clearAllDatabaseFromBefore` (localforage: ~3842 - 36% faster, Dexie: ~2600)
  * Not a method we will call frequently; and Dexie's implementation is actually the IndexedDB implementation, as I had trouble getting Dexie's to work.
* `setAll` (localforage: ~3866, Dexie: ~4270 - 9% faster)
* `getAll` (localforage: ~3502, Dexie: ~3917 - 10% faster)
* `setSingle` (localforage: ~16667, Dexie: ~23242 - 22% faster)
  * This is a method we use a lot.
* `setManySinglesBlocking` (localforage: ~no data, Dexie: ~no data)
  * This still crashed my browser at N = 100. We don't want to block anyway as row locking for Lightbeam is not a critical need when each website object is a key in our database.
*  `setManySinglesUnblocking` (localforage: ~116, Dexie: ~183 - 61% faster)
* `getRandomSet` (localforage: ~3481, Dexie: ~3850 - 11% faster)
* `getMostRecentSite`^^ (localforage: ~3892, Dexie: ~3836) - no difference
* `getLastThreeSites`^^ (localforage: ~4014, Dexie: ~3991) - no difference
* `getLastThreeDaysVisibleSites`^^ (localforage: ~3473, Dexie: ~3914 - 21% faster)
  * This is a very common joint query

^: Browser would crash on N = 10,000 websites for `getAll` and `setAll`. Writing and reading 10,000 entries from a database a hundred times is not the intended use case of this tool or Lightbeam.
^^: Now includes a `getAll` in localforage version

**Conclusion**: JSPerf tests each method against the other 50+ times and averages the results, so these results flatten out odd fluctuations, which is helpful. Dexie is still consistently faster in most cases, and especially for the methods we will use the most often.
